# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: check-docstring-first
  - id: check-toml
  - id: check-yaml
- repo: https://github.com/ambv/black
  rev: 22.3.0
  hooks:
  - id: black
- repo: https://gitlab.com/pycqa/flake8
  rev: 4.0.1
  hooks:
  - id: flake8
